const EPOCH_MIN = 5;
const EPOCH_MAX = 10;
const ITER_MIN = 500;
const ITER_MAX = 5000;
const PROB_MIN = 5;
const PROB_MAX = 10;
const GEN_NUM_MIN = 1;
const GEN_NUM_MAX = 100000;
const SEQ_MINLEN_MIN = 6;
const SEQ_MINLEN_MAX = 10;

export { EPOCH_MIN, EPOCH_MAX, ITER_MIN, ITER_MAX, PROB_MIN, PROB_MAX, 
    GEN_NUM_MIN, GEN_NUM_MAX, SEQ_MINLEN_MIN, SEQ_MINLEN_MAX}